### ISSUE TITLE
Best approach for updating recommendations?

### ISSUE THREAD

**Issue by joelhooks** [Pathgather/predictor#26]
I've got a website that has lessons, and I want to keep fresh predictions for my users. I base the recommendations on various things. Likes, users watching, related tags, etc and was wondering what is the recommended way to process recommendations to keep them fresh? When should I run `recommender.process!` vs updating individual lessons on their own? I'm using Heroku, and currently run `process!` once a day, but the docs don't give any advice in this regard.

Thank you in advance.

**Comment by jhdavids8** [comment]
Hey Joel,

If architected correctly, ``recommender.process!`` should rarely, if ever, be required. If you know the association of an action to a lesson, you should just be able to call ``recommender.process_item! lesson`` right after that action occurs. If your dataset is small enough, you can do this in the typical ``after_create`` hook (if in Rails) of the like, view, etc. If you're worried about that being slow, then you can just fire a worker up to run the ``process_item!`` call.

Hope that helps!

**Comment by joelhooks** [comment]
Thanks! I am doing it correctly, just wanted to be sure. We really appreciate this tool.

**Comment by jhdavids8** [comment]
Awesome, glad to hear it Joel!

**Comment by oleander** [comment]
Hi,

I'm having a bit of a problem related to this.

Updating a single record doesn't stand in direct relation (time wise) with updating the whole database. I currently have about 400k records in my engine. Running `Recommender#process!` takes about 14 min but updating a single record 'on-the-fly' using `Recommender#process_items!` takes 30 seconds. Is it suppose to take this long? From my benchmarks it would be much more beneficial (time wise) to just re-run `Recommender#process!` each night instead of doing `Recommender#process_items!` on each item for ~ 3000 * 30 sec every day (3000 == the amount of records that has to be updated every day), something that would take way to long time.

I'm I missing something?

**Comment by chanks** [comment]
Hi, sorry for the late reply, things have been a bit crazy around here recently :smile:. The time taken to process an item grows exponentially with the number of relations it has to other items, so if there are a few items in your dataset with many connections, it's expected that processing those items in particular will take a while. Is the 30 seconds figure the worst case or the average case that you've seen when processing individual items?

You might also try the :union processing technique if you haven't already - it's much faster than the :ruby (default) or :lua techniques, and the results it gives are roughly the same. See the README for more info on that.
